feat(tools): add android tool for sending push notifications using Deno
Unfortunately this errors with:
```
Error sending message:
Error: secretOrPrivateKey must be an asymmetric key when using RS256 at Object.module.exports
```

Will switch to Node.